name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/absdhjabwj/kernel_xiaomi_chopin
          kernel-branch: r
          config: chopin_currentgeek_defconfig
          arch: arm64
          aosp-gcc: true
          android-version: 11
          ksu-next: true
          other-clang-url: https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.tar.gz
          anykernel3: true
